# Generated by Django 4.2.4 on 2024-08-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estación')),
                ('address', models.CharField(max_length=50, null=True)),
                ('telephone', models.IntegerField()),
                ('coordinates', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
