# Generated by Django 4.2.4 on 2025-01-14 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sensor', '0001_initial'),
        ('Station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='stationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Station.station'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sensor.sensor'),
        ),
        migrations.AddField(
            model_name='actuator',
            name='stationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Station.station'),
        ),
    ]
